---
name: fail_telegram
trigger:
    type: timer
    interval: "20s"
notifiers:
    - name: printer
      type: print
    - name: telegram
      type: telegram
      token: ABCD
      chat_id: 1234
steps:
- notify:
    message: telegram saying Hi
    notifier: telegram
    upon_failure:
    - notify:
        message: Telegram failed but I'll write here
        notifier: printer